### ISSUE TITLE
can not compile on mac os x lion with node 0.6.0

### ISSUE THREAD

**Issue by odinliu** [creationix/node-leveldb#12]
odin@LionelMessi:~/buildspace/node-leveldb$ node-waf configure build
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : ok /usr/local/lib/node_modules 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.0 
'configure' finished successfully (0.098s)
Waf: Entering directory `/Users/odin/buildspace/node-leveldb/build'
[36/40] cxx: src/DB.cc -> build/Release/src/DB_1.o
[38/40] cxx: src/Iterator.cc -> build/Release/src/Iterator_1.o
../src/Iterator.cc: In static member function ‘static void node_leveldb::Iterator::EIO_BeforeSeekToFirst(node_leveldb::Iterator::SeekParams*)’:
../src/Iterator.cc:77: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Iterator.cc:77: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/Iterator.cc: In static member function ‘static void node_leveldb::Iterator::EIO_BeforeSeekToLast(node_leveldb::Iterator::SeekParams*)’:
../src/Iterator.cc:101: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Iterator.cc:101: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/DB.cc: In static member function ‘static void node_leveldb::DB::EIO_BeforeOpen(node_leveldb::DB::OpenParams*)’:
../src/DB.cc:104: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/DB.cc:104: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/DB.cc: In static member function ‘static void node_leveldb::DB::EIO_BeforeClose(node_leveldb::DB::Params*)’:
../src/DB.cc:157: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/DB.cc:157: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/Iterator.cc: In static member function ‘static void node_leveldb::Iterator::EIO_BeforeSeek(node_leveldb::Iterator::SeekParams*)’:
../src/Iterator.cc:132: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/Iterator.cc:132: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/DB.cc: In static member function ‘static void node_leveldb::DB::EIO_BeforeWrite(node_leveldb::DB::WriteParams*)’:
../src/DB.cc:320: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/DB.cc:320: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/DB.cc: In static member function ‘static void node_leveldb::DB::EIO_BeforeRead(node_leveldb::DB::ReadParams*)’:
../src/DB.cc:397: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/DB.cc:397: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
Waf: Leaving directory`/Users/odin/buildspace/node-leveldb/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx Iterator.cc -> Iterator_1.o}
 -> task failed (err #1): 
    {task: cxx DB.cc -> DB_1.o}

**Comment by gasteve** [comment]
I have the same issue on OSX 10.7.2 & node 0.6.8 … was this ever fixed?
